config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  #root "dashboard#index"
  get 'project/new'
  get 'projects' => 'project#index'

  post 'project/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title, message: ' field missing'
  validates_presence_of :client, message: ' field missing'
  validates_presence_of :project_type, message: ' field missing'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    puts "VGLOG : after sign in"
    projects_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    puts "VGLOG : after sign out"
    project_new_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if user_signed_in?
      redirect_to projects_path
    else
      redirect_to user_session_path
    end
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :get_all_projects, only: [:index, :create]

  def index 
  end

  def new 
    @project = Project.new
  end

  def create 
    proj_h = project_params 
    proj_h[:designer_email] = current_user.email
    @project = Project.new(proj_h)
    puts "New project : #{@project} : #{proj_h}"
    if @project.valid?
      @project.save
      redirect_to root_path
    else
      flash[:notice] = @project.errors.full_messages.first
      redirect_to project_new_path
    end
  end

  private 
    def get_all_projects
      #@projects = Project.all.sort_by(&:created_at).reverse
      @projects = Project.where(designer_email: current_user.email)
    end
    
    def project_params 
      params.require(:project).permit(:title, :client, :project_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    puts "+++++Current class : Helper: #{request.path} : #{test_path}"
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/dashboard/_main_content.html.erb
<!-- Page Content  -->
<p class="notice devise_alert_id"><%= notice %></p>
<p class="alert devise_alert_id"><%= alert %></p>

<div id="content">
  <nav class="navbar navbar-expand-sm navbar-dark bg-danger text-white"> 
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="#">
            SkpDesk
        </a>
    </li>
    </ul>
    <ul class="navbar-nav ml-auto" id="common_right_navbar">
    <li class="nav-item">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>
    </li>
    </ul>
  </nav>
</div>

app/views/dashboard/_sidebar.html.erb
<div class="btn"> 
  <span class="fas fa-bars"></span>
</div>
<nav class="sidebar">
    <div class="text"> BBBootstrap.com </div>
    <ul class="main_side">
      <li class="active"><a href="#">Dashboard</a></li>
      <li> <a href="#" id="1">Pages <span class="fas fa-caret-down"></span> </a>
          <ul class="item-show-1">
              <li><a href="#">Contact us</a></li>
              <li><a href="#">Our Team</a></li>
          </ul>
      </li>
      <li> <a href="#" id="2">Services <span class="fas fa-caret-down"></span> </a>
          <ul class="item-show-2">
              <li><a href="#">App Design</a></li>
              <li><a href="#">Web Design</a></li>
          </ul>
      </li>
      <li><a href="#">Users</a></li>
      <li><a href="#">Message</a></li>
      <li><a href="#">Bookmark</a></li>
      <li><a href="#">Files</a></li>
      <li>
        <%= link_to "All projects", projects_path %>
      </li>
      <li>
        <%= link_to "New project", project_new_path %>
      </li> 
    </ul>
</nav>

<script>
  $('.btn').click(function(){
    $(this).toggleClass("click");
    $('.sidebar').toggleClass("show");
  });


  $('.sidebar ul li a').click(function(){
    var id = $(this).attr('id');
    $('nav ul li ul.item-show-'+id).toggleClass("show");
    $('nav ul li #'+id+' span').toggleClass("rotate");

  });

  $('nav ul li').click(function(){
    $(this).addClass("active").siblings().removeClass("active");
  });
</script>

app/views/dashboard/_sidebar2.html.erb
<style>
  /*!
  * Start Bootstrap - Simple Sidebar HTML Template (https://startbootstrap.com)
  * Code licensed under the Apache License v2.0.
  * For details, see http://www.apache.org/licenses/LICENSE-2.0.
  */
  /* Toggle Styles */
  /* This sidebar modified by seegatesite.com */

  #wrapper {
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
  }

  #wrapper.toggled {
    padding-left: 250px;
  }

  #sidebar-wrapper {
    z-index: 1000;
    position: fixed;
    left: 250px;
    width: 0;
    height: 100%;
    margin-left: -250px;
    overflow-y: auto;
    background: #000;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
  }

  #wrapper.toggled #sidebar-wrapper {
    width: 250px;
  }

  #page-content-wrapper {
    width: 100%;
    position: absolute;
    padding: 15px;
  }

  #wrapper.toggled #page-content-wrapper {
    position: absolute;
    margin-right: -250px;
  }

  .fixed-brand {
    width: auto;
  }
  /* Sidebar Styles */

  .sidebar-nav {
    position: absolute;
    top: 0;
    width: 250px;
    margin: 0;
    padding: 0;
    list-style: none;
    margin-top: 2px;
  }

  .sidebar-nav li {
    text-indent: 15px;
    line-height: 40px;
  }

  .sidebar-nav li a {
    display: block;
    text-decoration: none;
    color: #FAFAFA;
  }

  .sidebar-nav li a:hover {
    text-decoration: none;
    color: #fff;
    background: rgba(255, 255, 255, 0.2);
    border-left: red 2px solid;
  }

  .sidebar-nav li a:active,
  .sidebar-nav li a:focus {
    text-decoration: none;
  }

  .sidebar-nav > .sidebar-brand {
    height: 65px;
    font-size: 18px;
    line-height: 60px;
  }

  .sidebar-nav > .sidebar-brand a {
    color: #999999;
  }

  .sidebar-nav > .sidebar-brand a:hover {
    color: #fff;
    background: none;
  }

  .no-margin {
    margin: 0;
  }

  @media(min-width:768px) {
    #wrapper {
      padding-left: 250px;
    }
    .fixed-brand {
      width: 250px;
    }
    #wrapper.toggled {
      padding-left: 0;
    }
    #sidebar-wrapper {
      width: 250px;
    }
    #wrapper.toggled #sidebar-wrapper {
      width: 250px;
    }
    #wrapper.toggled-2 #sidebar-wrapper {
      width: 150px;
    }
    #wrapper.toggled-2 #sidebar-wrapper:hover {
      width: 250px;
    }
    #page-content-wrapper {
      padding: 20px;
      position: relative;
      -webkit-transition: all 0.5s ease;
      -moz-transition: all 0.5s ease;
      -o-transition: all 0.5s ease;
      transition: all 0.5s ease;
    }
    #wrapper.toggled #page-content-wrapper {
      position: relative;
      margin-right: 0;
      padding-left: 250px;
    }
    #wrapper.toggled-2 #page-content-wrapper {
      position: relative;
      margin-right: 0;
      margin-left: -200px;
      -webkit-transition: all 0.5s ease;
      -moz-transition: all 0.5s ease;
      -o-transition: all 0.5s ease;
      transition: all 0.5s ease;
    }
  }
</style>

<script>
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });
  $("#menu-toggle-2").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled-2");
    $('#menu ul').hide();
  });

  function initMenu() {
    $('#menu ul').hide();
    $('#menu ul').children('.current').parent().show();
    //$('#menu ul:first').show();
    $('#menu li a').click(
      function() {
        var checkElement = $(this).next();
        if ((checkElement.is('ul')) && (checkElement.is(':visible'))) {
          return false;
        }
        if ((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
          $('#menu ul:visible').slideUp('normal');
          checkElement.slideDown('normal');
          return false;
        }
      }
    );
  }
  $(document).ready(function() {
    initMenu();
  });
</script>


<div id="wrapper">
  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav nav-pills nav-stacked" id="menu">

      <li class="active">
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-dashboard fa-stack-1x "></i></span> Dashboard</a>
      </li>
      <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span> Shortcut</a>
      </li>
      <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cloud-download fa-stack-1x "></i></span>Overview</a>
      </li>
      <li>
        <a href="#"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-cart-plus fa-stack-1x "></i></span>Events</a>
      </li>
      <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-youtube-play fa-stack-1x "></i></span>About</a>
      </li>
      <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-wrench fa-stack-1x "></i></span>Services</a>
      </li>
      <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
      </li>
    </ul>
  </div>
  <%= render partial: 'dashboard/main_content' %>
</div>
<!-- /#wrapper -->
<!-- jQuery -->

app/views/dashboard/_sidebar3.html.erb
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
      <div class="sidebar-header">
          <h3>SkpDesk</h3>
          <strong>BS</strong>
      </div>

      <ul class="list-unstyled components">
          <li>
            <%= link_to "All projects", projects_path %>
          </li>
          <li>
            <%= link_to "New project", project_new_path %>
          </li> 
      </ul>

      
      <div id="user_profile_div">
        <hr>
        <%= button_to "Signout", destroy_user_session_path, method: :delete  %>
        <div id="user_email_div">
          <%= current_user.email %>
        </div>
      </div>
  </nav>

  <div id="content">
    <%= yield %>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            //$('#sidebar').toggleClass('active');
             $(this).addClass('active').siblings().removeClass('active');
        });

        //Not working recheck
        $('#sidebar ul li').on('click', function() {
            $(this).addClass('active').siblings().removeClass('active');
        });
    });
</script>


<%= 
=begin

Dropdown 

<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
    <i class="fas fa-copy"></i>
    Pages
</a>
<ul class="collapse list-unstyled" id="pageSubmenu">
    <li>
        <a href="#">Page 1</a>
    </li>
    <li>
        <a href="#">Page 2</a>
    </li>
    <li>
        <a href="#">Page 3</a>
    </li>
</ul>
=end
%>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skpdesk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>
    <%
=begin%>
 <%= stylesheet_link_tag 'main_layout' %> 
<%
=end%>
    <%= stylesheet_link_tag 'sidebar3' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
        /* #common_right_navbar {
            margin-left: auto;
        }
        .active{
          color: red;
        } */

          #user_profile_div{
            position: absolute;
            bottom: 0;
          }
          #sidebar, #user_profile_div {
            word-wrap: break-word;
          }
          #user_email_div {
            word-wrap: break-word;
            overflow:hidden;
          }
    </style>
    <script>
      $(document).ready(function () {
        $(".nav a").on("click", function() {
          alert("Hi...00");
          $(".nav").find(".active").removeClass("active");
          $(this).parent().addClass("active");
        });
      });
    </script>

    <%# Yield all the head codes here! %>
    <% if content_for?(:head) %>
        <%= yield(:head) %>
    <% end %> 
  </head>

  <body>  
    <% if current_user %> 
      <%= render partial: "dashboard/sidebar3" %>
    <% else %>
      <%= render template: "/devise/sessions/new" %>
    <% end %>
  </body>
</html>

app/views/project/index.html.erb
<div id="project_list">
  <div id="project_top">
    <h1> Project list</h1>
  </div>

  <div>
    <table class="table table-dark table-bordered">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Email</th>
          <th scope="col">Type</th>
          <th scope="col">Designer </th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td> <%= project.title %> </td>
            <td> <%= project.client %> </td>
            <td> <%= project.project_type %> </td>
            <td> <%= project.designer_email %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>  
    <%= button_to "New Project", project_new_path , class: "btn btn-success btn-lg float-end", method: :get%>
  </div>
</div>

app/views/project/new.html.erb
<style>
  .devise_alert_id {
    display: none;
  }
</style>
<script type="text/javascript">
  $(function() {
    $('.devise_alert_id').hide();
    //$('.alert').slideUp(1500);
    $('.alert').fadeOut(3000);
  });
</script>

<h1>Create Project</h1>
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
<div id="create_project">
  <%= form_for @project, url: project_create_path do |f| %>
    <div class="form-group row">
      <div class="col-5">
        <%= f.label       :title, 'Project Title', class: "col-sm-4 col-form-label"%>
        <%= f.text_field  :title     %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-5">
        <%= f.label       :client, 'Client mail', class: "col-sm-4 col-form-label" %>
        <%= f.text_field  :client    %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-5">
        <%= f.label       :project_type, 'Project Type', class: "col-sm-4 col-form-label" %>
        <%= f.text_field  :project_type      %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <div class="col-2">
        <%= f.submit "Create project", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>